language: ruby
rvm:
  - 2.1.2
before_script:
  - psql -c 'create database weby_test;' -U postgres
  - mv config/travis_database.yml config/database.yml
  - rm -rf vendor/bundle/ruby/2.1.2/gems/i18n-0.6.9/test
  - RAILS_ENV=test bundle exec rake --trace db:schema:load
script: bundle exec rspec spec
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/d2f9a0264425ceca43de
    on_success: always
    on_failure: always
    on_start: false
