language: ruby
rvm:
  - 2.1.0
before_script:
  - psql -c 'create database weby_test;' -U postgres
  - mv config/travis_database.yml config/database.yml
  - rm -rf vendor/bundle/ruby/2.1.0/gems/i18n-0.6.9/test
  - RAILS_ENV=test bundle exec rake --trace db:schema:load
script: bundle exec rspec spec
