language: ruby
rvm:
- 2.5.7
stages:
  - build
  - deploy
services:
  # - test
  - docker
  - postgresql
env:
  - AWS_ECR=$AWS_ACCOUNT_ID.dkr.ecr.ap-south-1.amazonaws.com/weby 
before_script:
- pip install -U pip
- pip install awscli
- echo $TRAVIS_COMMIT
- echo $AWS_ECR
- aws ecr get-login-password --region ap-south-1| docker login --username AWS --password-stdin 830507477504.dkr.ecr.ap-south-1.amazonaws.com
# - RAILS_ENV=test bundle exec rake --trace db:schema:load
# script: bin/rspec spec
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/d2f9a0264425ceca43de
    on_success: always
    on_failure: always
  slack:
    secure: zxImXQ03YcFxIRY3GiRBEslkZPrfulnFq5t7MjJNCWZsfNOyLxqCzFDHISedgh4TGkrUXE9/5Z1KDb0du7FK14sjoDfHMCru2cJdZBdZ/vIYoub6cafM0yrGK0/YawqWqQFFW6lGazG1D0tmkFZS6JduO2FYMlwgqwOh9zM9w8w=

jobs:
  include:
    # - stage: test
    #   name: "Build docker images"
    #   # script: 
    #   #   - psql -c 'create database weby_test;' -U postgres
    #   #   - mv config/travis_database.yml config/database.yml
    #   #   - mv config/secrets.yml.example config/secrets.yml
    #   #   - RAILS_ENV=test bundle exec rake --trace db:schema:load
    #   #   - bin/rspec spec
    - stage: build
      name: "Build docker images"
      script:
        - mv config/travis_database.yml config/database.yml
        - mv config/secrets.yml.example config/secrets.yml
        - docker build -t $AWS_ACCOUNT_ID.dkr.ecr.ap-south-1.amazonaws.com/weby:$TRAVIS_COMMIT .
        - docker tag $AWS_ACCOUNT_ID.dkr.ecr.ap-south-1.amazonaws.com/weby:$TRAVIS_COMMIT $AWS_ACCOUNT_ID.dkr.ecr.ap-south-1.amazonaws.com/weby:latest        
        - docker push $AWS_ACCOUNT_ID.dkr.ecr.ap-south-1.amazonaws.com/weby:$TRAVIS_COMMIT
        - docker push $AWS_ACCOUNT_ID.dkr.ecr.ap-south-1.amazonaws.com/weby:latest

    - stage: deploy
      name: "Deploy to AWS"
      script: 
        - aws cloudformation create-stack --stack-name weby-cft --template-url  https://cf-templates-lq1fztl5lj2k-ap-south-1.s3.ap-south-1.amazonaws.com/20211877hL-weby-cft-2.yaml --capabilities CAPABILITY_NAMED_IAM