development:
  this2:
    width: 500
    placeholders:
      - names: ['first_place']
      - names: ['top']
      - names: ['left', 'home']
        height: 190
        width: [30,70]
      - names: ['bottom']


