#Settings
#
#per_page: opções de escolha de quantidade de itens por página em listagens
#per_page_default: padrão de itens por página em listagens
#default_locale: idioma padrão
#help_site: url do site para o link 'ajuda'
#tld_length: tamanho do domínio onde o weby está rodando Ex: 'weby.com.br' tld_length=2, 'weby.br' tld_length=1(padrão)
#sites_index: site_id para mostrar a listagem dos sites, se não existir essa propriedade será o root do domínio
#login_protocol: protocolo da página de login (opções 'http' e 'https', padrão=http)
#
per_page:
  id: 1
  name: 'per_page'
  value: '5,15,30,60,100'

per_page_default:
  id: 2
  name: 'per_page_default'
  value: '25'

default_locale:
  id: 3
  name: 'default_locale'
  value: 'pt-BR'

help_site:
  id: 4
  name: 'help_site'
  value: '/help'

tld_length:
  id: 5
  name: 'tld_length'
  value: '1'
