#Settings
#
#
per_page:
  id: 1
  name: 'per_page'
  value: '5,15,30,60,100'

per_page_default:
  id: 2
  name: 'per_page_default'
  value: '25'

default_locale:
  id: 3
  name: 'default_locale'
  value: 'pt-BR'

help_site:
  id: 4
  name: 'help_site'
  value: '/help'

tld_length:
  id: 5
  name: 'tld_length'
  value: '1'

clipping_per_days:
  id: 6
  name: 'clipping_per_days'
  value: '7'
